export const IMAGES = {
  home_banner: require("../assets/images/e-learning.png"),
  program_banner: require("../assets/images/programs-en-pc.png"),
  program_img_1: require("../assets/images/khoa-hoc-tieng-anh-online-1.png"),
  program_describe_image: require("../assets/images/img-1.png"),
  teacher_portrait: require("../assets/images/chup-anh-chan-dung-co-giao-thay-giao-giao-vien-o-ha-noi-studio-yeu-media-phuc-vu-nha-truong-school-06.webp"),
  ceo_image: require("../assets/images/ceo-image.png"),
  student1_image: require("../assets/images/img_2.png"),
  student2_image: require("../assets/images/img_3.png"),
  student_dashboard_header: require("../assets/images/student-dashboard-header.png"),
  group_image: require("../assets/images/Group.png"),
  france_image: require("../assets/images/France.png"),
  completedClassImage: require("../assets/images/completedClass.svg").default,
  evaluationImage: require("../assets/images/evaluation.svg").default,
  incomeIcon: require("../assets/images/income-icon-money.svg").default,
};
